// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: Server.proto

package Server_Helper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Betas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ammount int64 `protobuf:"varint,1,opt,name=ammount,proto3" json:"ammount,omitempty"`
}

func (x *Betas) Reset() {
	*x = Betas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Betas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Betas) ProtoMessage() {}

func (x *Betas) ProtoReflect() protoreflect.Message {
	mi := &file_Server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Betas.ProtoReflect.Descriptor instead.
func (*Betas) Descriptor() ([]byte, []int) {
	return file_Server_proto_rawDescGZIP(), []int{0}
}

func (x *Betas) GetAmmount() int64 {
	if x != nil {
		return x.Ammount
	}
	return 0
}

type To_Inscribe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inscribed int64  `protobuf:"varint,1,opt,name=inscribed,proto3" json:"inscribed,omitempty"`
	Server    string `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *To_Inscribe) Reset() {
	*x = To_Inscribe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *To_Inscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*To_Inscribe) ProtoMessage() {}

func (x *To_Inscribe) ProtoReflect() protoreflect.Message {
	mi := &file_Server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use To_Inscribe.ProtoReflect.Descriptor instead.
func (*To_Inscribe) Descriptor() ([]byte, []int) {
	return file_Server_proto_rawDescGZIP(), []int{1}
}

func (x *To_Inscribe) GetInscribed() int64 {
	if x != nil {
		return x.Inscribed
	}
	return 0
}

func (x *To_Inscribe) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

var File_Server_proto protoreflect.FileDescriptor

var file_Server_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x22, 0x21, 0x0a,
	0x05, 0x42, 0x65, 0x74, 0x61, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6d, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x6d, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x43, 0x0a, 0x0b, 0x74, 0x6f, 0x5f, 0x49, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x32, 0x52, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f,
	0x49, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x12, 0x3e, 0x0a, 0x08, 0x49, 0x6e, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x14, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x68,
	0x65, 0x6c, 0x70, 0x65, 0x72, 0x2e, 0x42, 0x65, 0x74, 0x61, 0x73, 0x1a, 0x1a, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x5f, 0x49,
	0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x61, 0x73, 0x74, 0x69, 0x68, 0x61, 0x6e,
	0x2d, 0x43, 0x68, 0x69, 0x72, 0x69, 0x6e, 0x6f, 0x46, 0x2f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x48, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Server_proto_rawDescOnce sync.Once
	file_Server_proto_rawDescData = file_Server_proto_rawDesc
)

func file_Server_proto_rawDescGZIP() []byte {
	file_Server_proto_rawDescOnce.Do(func() {
		file_Server_proto_rawDescData = protoimpl.X.CompressGZIP(file_Server_proto_rawDescData)
	})
	return file_Server_proto_rawDescData
}

var file_Server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Server_proto_goTypes = []interface{}{
	(*Betas)(nil),       // 0: Server_helper.Betas
	(*To_Inscribe)(nil), // 1: Server_helper.to_Inscribe
}
var file_Server_proto_depIdxs = []int32{
	0, // 0: Server_helper.Report_Inscribed.Inscribe:input_type -> Server_helper.Betas
	1, // 1: Server_helper.Report_Inscribed.Inscribe:output_type -> Server_helper.to_Inscribe
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Server_proto_init() }
func file_Server_proto_init() {
	if File_Server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Betas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*To_Inscribe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Server_proto_goTypes,
		DependencyIndexes: file_Server_proto_depIdxs,
		MessageInfos:      file_Server_proto_msgTypes,
	}.Build()
	File_Server_proto = out.File
	file_Server_proto_rawDesc = nil
	file_Server_proto_goTypes = nil
	file_Server_proto_depIdxs = nil
}
